export const CLEAN_UP = "CLEAN_UP"

export const FETCH_SEATS_REQUEST = "FETCH_SEATS_REQUEST"
export const FETCH_SEATS_SUCCESS = "FETCH_SEATS_SUCCESS"
export const FETCH_SEATS_FAILURE = "FETCH_SEATS_FAILURE"

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"

export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE = "LOG_IN_FAILURE"

export const LOG_OUT = "LOG_OUT"

export const MAKE_RESERVATION_REQUEST = "MAKE_RESERVATION_REQUEST"
export const MAKE_RESERVATION_SUCCESS = "MAKE_RESERVATION_SUCCESS"
export const MAKE_RESERVATION_FAILURE = "MAKE_RESERVATION_FAILURE"

export const GET_RESERVATION_REQUEST = "GET_RESERVATION_REQUEST"
export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS"
export const GET_RESERVATION_FAILURE = "GET_RESERVATION_FAILURE"

export const CANCEL_RESERVATION_REQUEST = "CANCEL_RESERVATION_REQUEST"
export const CANCEL_RESERVATION_SUCCESS = "CANCEL_RESERVATION_SUCCESS"
export const CANCEL_RESERVATION_FAILURE = "CANCEL_RESERVATION_FAILURE"
